// Widen NODE_ENV from the literal "development" generated by wrangler types.
// At deploy time, --var NODE_ENV:production overrides it.
declare global {
  // biome-ignore lint/style/noNamespace: required for NodeJS.ProcessEnv augmentation
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: string;
    }
  }
}

// Service bindings exposed to the apps/app worker. These are populated by
// `wrangler.jsonc` `services` entries; declared here so handler code can
// type-check before wrangler runtime types are generated.
declare global {
  interface CloudflareBindings {
    API: Fetcher;
    ASSETS: Fetcher;
    // Injected via `--var NODE_ENV:production`; gates dev-only edge headers.
    NODE_ENV?: string;
  }
}

export type {};
