/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInviteInvitationIdRouteImport } from './routes/accept-invite/$invitationId'

const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: '/accept-invite/$invitationId',
    path: '/accept-invite/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/accept-invite/$invitationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/accept-invite/$invitationId'
  id: '__root__' | '/accept-invite/$invitationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invite/$invitationId': {
      id: '/accept-invite/$invitationId'
      path: '/accept-invite/$invitationId'
      fullPath: '/accept-invite/$invitationId'
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
