/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as protectedHelpCenterRouteRouteImport } from './routes/(protected)/help-center/route'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as Errors401RouteImport } from './routes/errors/401'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors503RouteImport } from './routes/errors/503'
import { Route as protectedAuditLogsIndexRouteImport } from './routes/(protected)/audit-logs/index'
import { Route as protectedDashboardIndexRouteImport } from './routes/(protected)/dashboard/index'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedSettingsAppearanceRouteImport } from './routes/(protected)/settings/appearance'
import { Route as protectedSettingsNotificationsRouteImport } from './routes/(protected)/settings/notifications'
import { Route as protectedUsersIndexRouteImport } from './routes/(protected)/users/index'
import { Route as protectedUsersUserIdRouteImport } from './routes/(protected)/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedHelpCenterRouteRoute =
  protectedHelpCenterRouteRouteImport.update({
    id: '/help-center',
    path: '/help-center',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const Errors401Route = Errors401RouteImport.update({
  id: '/errors/401',
  path: '/errors/401',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors503Route = Errors503RouteImport.update({
  id: '/errors/503',
  path: '/errors/503',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedAuditLogsIndexRoute = protectedAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardIndexRoute = protectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedSettingsRouteRoute,
} as any)
const protectedSettingsAppearanceRoute =
  protectedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsNotificationsRoute =
  protectedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedUsersIndexRoute = protectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedUsersUserIdRoute = protectedUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/help-center': typeof protectedHelpCenterRouteRoute
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/settings/appearance': typeof protectedSettingsAppearanceRoute
  '/settings/notifications': typeof protectedSettingsNotificationsRoute
  '/users/$userId': typeof protectedUsersUserIdRoute
  '/audit-logs/': typeof protectedAuditLogsIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/users/': typeof protectedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/help-center': typeof protectedHelpCenterRouteRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/settings/appearance': typeof protectedSettingsAppearanceRoute
  '/settings/notifications': typeof protectedSettingsNotificationsRoute
  '/users/$userId': typeof protectedUsersUserIdRoute
  '/audit-logs': typeof protectedAuditLogsIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/users': typeof protectedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(protected)/help-center': typeof protectedHelpCenterRouteRoute
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/(protected)/settings/appearance': typeof protectedSettingsAppearanceRoute
  '/(protected)/settings/notifications': typeof protectedSettingsNotificationsRoute
  '/(protected)/users/$userId': typeof protectedUsersUserIdRoute
  '/(protected)/audit-logs/': typeof protectedAuditLogsIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(protected)/users/': typeof protectedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/help-center'
    | '/settings'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/users/$userId'
    | '/audit-logs/'
    | '/dashboard/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/help-center'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/users/$userId'
    | '/audit-logs'
    | '/dashboard'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/login'
    | '/(protected)/help-center'
    | '/(protected)/settings'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/(protected)/settings/appearance'
    | '/(protected)/settings/notifications'
    | '/(protected)/users/$userId'
    | '/(protected)/audit-logs/'
    | '/(protected)/dashboard/'
    | '/(protected)/settings/'
    | '/(protected)/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
  Errors503Route: typeof Errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/help-center': {
      id: '/(protected)/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof protectedHelpCenterRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/errors/401': {
      id: '/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof Errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/503': {
      id: '/errors/503'
      path: '/errors/503'
      fullPath: '/errors/503'
      preLoaderRoute: typeof Errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/audit-logs/': {
      id: '/(protected)/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof protectedAuditLogsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/appearance': {
      id: '/(protected)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof protectedSettingsAppearanceRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/notifications': {
      id: '/(protected)/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof protectedSettingsNotificationsRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/users/': {
      id: '/(protected)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof protectedUsersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/users/$userId': {
      id: '/(protected)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof protectedUsersUserIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedSettingsRouteRouteChildren {
  protectedSettingsAppearanceRoute: typeof protectedSettingsAppearanceRoute
  protectedSettingsNotificationsRoute: typeof protectedSettingsNotificationsRoute
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsAppearanceRoute: protectedSettingsAppearanceRoute,
    protectedSettingsNotificationsRoute: protectedSettingsNotificationsRoute,
    protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedHelpCenterRouteRoute: typeof protectedHelpCenterRouteRoute
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedUsersUserIdRoute: typeof protectedUsersUserIdRoute
  protectedAuditLogsIndexRoute: typeof protectedAuditLogsIndexRoute
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedUsersIndexRoute: typeof protectedUsersIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedHelpCenterRouteRoute: protectedHelpCenterRouteRoute,
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedUsersUserIdRoute: protectedUsersUserIdRoute,
  protectedAuditLogsIndexRoute: protectedAuditLogsIndexRoute,
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedUsersIndexRoute: protectedUsersIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
  Errors503Route: Errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
