// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ActivateUserData, ActivateUserErrors, ActivateUserResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeactivateUserData, DeactivateUserErrors, DeactivateUserResponses, DeletePushTokenData, DeletePushTokenErrors, DeletePushTokenResponses, GetAuthorizationCapabilitiesData, GetAuthorizationCapabilitiesErrors, GetAuthorizationCapabilitiesResponses, GetMyAccountData, GetMyAccountErrors, GetMyAccountResponses, GetNotificationData, GetNotificationErrors, GetNotificationPreferencesData, GetNotificationPreferencesErrors, GetNotificationPreferencesResponses, GetNotificationResponses, GetUnreadNotificationCountData, GetUnreadNotificationCountErrors, GetUnreadNotificationCountResponses, GetUserData, GetUserErrors, GetUserResponses, ListAuditLogsData, ListAuditLogsErrors, ListAuditLogsResponses, ListNotificationsData, ListNotificationsErrors, ListNotificationsResponses, ListPushTokensData, ListPushTokensErrors, ListPushTokensResponses, ListRolesData, ListRolesErrors, ListRolesResponses, ListUsersData, ListUsersErrors, ListUsersResponses, MarkAllNotificationsAsReadData, MarkAllNotificationsAsReadErrors, MarkAllNotificationsAsReadResponses, MarkNotificationAsReadData, MarkNotificationAsReadErrors, MarkNotificationAsReadResponses, RegisterPushTokenData, RegisterPushTokenErrors, RegisterPushTokenResponses, UnlockUserData, UnlockUserErrors, UnlockUserResponses, UpdateNotificationPreferencesData, UpdateNotificationPreferencesErrors, UpdateNotificationPreferencesResponses, UpdateUserData, UpdateUserErrors, UpdateUserResponses, UpdateUserRolesData, UpdateUserRolesErrors, UpdateUserRolesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List all roles
 *
 * Returns a list of all system roles
 */
export const listRoles = <ThrowOnError extends boolean = true>(options?: Options<ListRolesData, ThrowOnError>): RequestResult<ListRolesResponses, ListRolesErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ListRolesResponses, ListRolesErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/roles',
    ...options
});

/**
 * List users
 *
 * Returns a paginated list of users with optional filters
 */
export const listUsers = <ThrowOnError extends boolean = true>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users',
    ...options
});

/**
 * Create user
 *
 * Creates a new user with the specified details
 */
export const createUser = <ThrowOnError extends boolean = true>(options?: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError, 'data'> => (options?.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get my profile summary
 *
 * Returns user-facing profile info and notification summary
 */
export const getMyAccount = <ThrowOnError extends boolean = true>(options?: Options<GetMyAccountData, ThrowOnError>): RequestResult<GetMyAccountResponses, GetMyAccountErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<GetMyAccountResponses, GetMyAccountErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/me',
    ...options
});

/**
 * Get user by ID
 *
 * Returns detailed user information
 */
export const getUser = <ThrowOnError extends boolean = true>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError, 'data'> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}',
    ...options
});

/**
 * Update user
 *
 * Updates user profile information
 */
export const updateUser = <ThrowOnError extends boolean = true>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).patch<UpdateUserResponses, UpdateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update user roles
 *
 * Updates user role assignments
 */
export const updateUserRoles = <ThrowOnError extends boolean = true>(options: Options<UpdateUserRolesData, ThrowOnError>): RequestResult<UpdateUserRolesResponses, UpdateUserRolesErrors, ThrowOnError, 'data'> => (options.client ?? client).patch<UpdateUserRolesResponses, UpdateUserRolesErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}/roles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deactivate user
 *
 * Deactivates a user and revokes all sessions
 */
export const deactivateUser = <ThrowOnError extends boolean = true>(options: Options<DeactivateUserData, ThrowOnError>): RequestResult<DeactivateUserResponses, DeactivateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<DeactivateUserResponses, DeactivateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}/deactivate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Activate user
 *
 * Reactivates a deactivated user
 */
export const activateUser = <ThrowOnError extends boolean = true>(options: Options<ActivateUserData, ThrowOnError>): RequestResult<ActivateUserResponses, ActivateUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<ActivateUserResponses, ActivateUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}/activate',
    ...options
});

/**
 * Unlock user
 *
 * Unlocks a locked user and resets failed login attempts
 */
export const unlockUser = <ThrowOnError extends boolean = true>(options: Options<UnlockUserData, ThrowOnError>): RequestResult<UnlockUserResponses, UnlockUserErrors, ThrowOnError, 'data'> => (options.client ?? client).post<UnlockUserResponses, UnlockUserErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/users/{userId}/unlock',
    ...options
});

/**
 * List audit logs
 *
 * Returns a paginated list of audit logs with optional filters
 */
export const listAuditLogs = <ThrowOnError extends boolean = true>(options?: Options<ListAuditLogsData, ThrowOnError>): RequestResult<ListAuditLogsResponses, ListAuditLogsErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ListAuditLogsResponses, ListAuditLogsErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/audit-logs',
    ...options
});

/**
 * List notifications
 *
 * Returns a paginated list of notifications for the authenticated user
 */
export const listNotifications = <ThrowOnError extends boolean = true>(options?: Options<ListNotificationsData, ThrowOnError>): RequestResult<ListNotificationsResponses, ListNotificationsErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ListNotificationsResponses, ListNotificationsErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications',
    ...options
});

/**
 * Get notification preferences
 *
 * Returns notification preferences for the authenticated user
 */
export const getNotificationPreferences = <ThrowOnError extends boolean = true>(options?: Options<GetNotificationPreferencesData, ThrowOnError>): RequestResult<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<GetNotificationPreferencesResponses, GetNotificationPreferencesErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/preferences',
    ...options
});

/**
 * Update notification preferences
 *
 * Updates notification preferences for the authenticated user
 */
export const updateNotificationPreferences = <ThrowOnError extends boolean = true>(options?: Options<UpdateNotificationPreferencesData, ThrowOnError>): RequestResult<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError, 'data'> => (options?.client ?? client).patch<UpdateNotificationPreferencesResponses, UpdateNotificationPreferencesErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/preferences',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get notification details
 *
 * Returns details of a specific notification
 */
export const getNotification = <ThrowOnError extends boolean = true>(options: Options<GetNotificationData, ThrowOnError>): RequestResult<GetNotificationResponses, GetNotificationErrors, ThrowOnError, 'data'> => (options.client ?? client).get<GetNotificationResponses, GetNotificationErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/{notificationId}',
    ...options
});

/**
 * Get unread notification count
 *
 * Returns the number of unread notifications for the user
 */
export const getUnreadNotificationCount = <ThrowOnError extends boolean = true>(options?: Options<GetUnreadNotificationCountData, ThrowOnError>): RequestResult<GetUnreadNotificationCountResponses, GetUnreadNotificationCountErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<GetUnreadNotificationCountResponses, GetUnreadNotificationCountErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/unread/count',
    ...options
});

/**
 * Mark notification as read
 *
 * Marks a specific notification as read
 */
export const markNotificationAsRead = <ThrowOnError extends boolean = true>(options: Options<MarkNotificationAsReadData, ThrowOnError>): RequestResult<MarkNotificationAsReadResponses, MarkNotificationAsReadErrors, ThrowOnError, 'data'> => (options.client ?? client).post<MarkNotificationAsReadResponses, MarkNotificationAsReadErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/{notificationId}/read',
    ...options
});

/**
 * Mark all notifications as read
 *
 * Marks all notifications as read for the authenticated user
 */
export const markAllNotificationsAsRead = <ThrowOnError extends boolean = true>(options?: Options<MarkAllNotificationsAsReadData, ThrowOnError>): RequestResult<MarkAllNotificationsAsReadResponses, MarkAllNotificationsAsReadErrors, ThrowOnError, 'data'> => (options?.client ?? client).post<MarkAllNotificationsAsReadResponses, MarkAllNotificationsAsReadErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/read-all',
    ...options
});

/**
 * List push tokens
 *
 * Returns all registered push tokens for the authenticated user
 */
export const listPushTokens = <ThrowOnError extends boolean = true>(options?: Options<ListPushTokensData, ThrowOnError>): RequestResult<ListPushTokensResponses, ListPushTokensErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<ListPushTokensResponses, ListPushTokensErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/push-tokens',
    ...options
});

/**
 * Register push token
 *
 * Registers a new push token for the authenticated user's device
 */
export const registerPushToken = <ThrowOnError extends boolean = true>(options?: Options<RegisterPushTokenData, ThrowOnError>): RequestResult<RegisterPushTokenResponses, RegisterPushTokenErrors, ThrowOnError, 'data'> => (options?.client ?? client).post<RegisterPushTokenResponses, RegisterPushTokenErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/push-tokens',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete push token
 *
 * Deactivates a push token for the authenticated user
 */
export const deletePushToken = <ThrowOnError extends boolean = true>(options: Options<DeletePushTokenData, ThrowOnError>): RequestResult<DeletePushTokenResponses, DeletePushTokenErrors, ThrowOnError, 'data'> => (options.client ?? client).delete<DeletePushTokenResponses, DeletePushTokenErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/notifications/push-tokens/{tokenId}',
    ...options
});

/**
 * Get current user authorization capabilities
 */
export const getAuthorizationCapabilities = <ThrowOnError extends boolean = true>(options?: Options<GetAuthorizationCapabilitiesData, ThrowOnError>): RequestResult<GetAuthorizationCapabilitiesResponses, GetAuthorizationCapabilitiesErrors, ThrowOnError, 'data'> => (options?.client ?? client).get<GetAuthorizationCapabilitiesResponses, GetAuthorizationCapabilitiesErrors, ThrowOnError, 'data'>({
    responseStyle: 'data',
    url: '/api/authorization/capabilities',
    ...options
});
