// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ListRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/roles';
};

export type ListRolesErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
  /**
   * Roles
   */
  200: {
    roles: Array<{
      description: string;
      name: string;
      permissions: Array<'dashboard:access' | 'users:view' | 'users:create' | 'users:update' | 'users:delete' | 'users:deactivate' | 'users:activate' | 'users:unlock' | 'roles:view' | 'roles:update' | 'audit-logs:view'>;
      slug: string;
    }>;
  };
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by role slug
     */
    role?: string;
    /**
     * Search by name or email
     */
    search?: string;
    /**
     * Sort by column
     */
    sort?: string;
    /**
     * Filter by status
     */
    status?: 'active' | 'deleted' | 'inactive' | 'locked';
    /**
     * Sort order
     */
    order?: 'asc' | 'desc';
    /**
     * Page number (1-indexed)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    perPage?: number;
  };
  url: '/api/users';
};

export type ListUsersErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
  /**
   * Paginated users list
   */
  200: {
    data: Array<{
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      roleSlugs: Array<string>;
      status: 'active' | 'deleted' | 'inactive' | 'locked';
      updatedAt: string;
    }>;
    meta: {
      /**
       * Whether there is a next page
       */
      hasNext: boolean;
      /**
       * Whether there is a previous page
       */
      hasPrev: boolean;
      /**
       * Next page number or null
       */
      nextPage: number | null;
      /**
       * Current page number
       */
      page: number;
      /**
       * Total number of pages
       */
      pageCount: number;
      /**
       * Items per page
       */
      perPage: number;
      /**
       * Previous page number or null
       */
      prevPage: number | null;
      /**
       * Total number of items
       */
      total: number;
    };
  };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body?: {
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    name: string;
    /**
     * Initial password (min 8 characters)
     */
    password: string;
    /**
     * Role slugs to assign
     */
    roleSlugs: Array<string>;
  };
  path?: never;
  query?: never;
  url: '/api/users';
};

export type CreateUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  /**
   * User created
   */
  201: {
    user: {
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      roleSlugs: Array<string>;
      status: 'active' | 'deleted' | 'inactive' | 'locked';
      updatedAt: string;
    };
  };
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type GetMyAccountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/users/me';
};

export type GetMyAccountErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type GetMyAccountError = GetMyAccountErrors[keyof GetMyAccountErrors];

export type GetMyAccountResponses = {
  /**
   * Current user account
   */
  200: {
    notifications: {
      unreadCount: number;
    };
    profile: {
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      onboardingCompletedAt: string | null;
      updatedAt: string;
    };
  };
};

export type GetMyAccountResponse = GetMyAccountResponses[keyof GetMyAccountResponses];

export type GetUserData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}';
};

export type GetUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
  /**
   * User details
   */
  200: {
    user: {
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      roleSlugs: Array<string>;
      status: 'active' | 'deleted' | 'inactive' | 'locked';
      updatedAt: string;
      deactivatedAt: string | null;
      deactivatedBy: string | null;
      deactivatedReason: string | null;
      failedLoginAttempts: number;
      lockedUntil: string | null;
    };
  };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
  body?: {
    name?: string;
  };
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}';
};

export type UpdateUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  /**
   * User updated
   */
  200: {
    user: {
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      roleSlugs: Array<string>;
      status: 'active' | 'deleted' | 'inactive' | 'locked';
      updatedAt: string;
    };
  };
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type UpdateUserRolesData = {
  body?: {
    /**
     * New role slugs (replaces existing)
     */
    roleSlugs: Array<string>;
  };
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}/roles';
};

export type UpdateUserRolesErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type UpdateUserRolesError = UpdateUserRolesErrors[keyof UpdateUserRolesErrors];

export type UpdateUserRolesResponses = {
  /**
   * Roles updated
   */
  200: {
    user: {
      createdAt: string;
      email: string;
      emailVerified: boolean;
      id: string;
      image: string | null;
      name: string;
      roleSlugs: Array<string>;
      status: 'active' | 'deleted' | 'inactive' | 'locked';
      updatedAt: string;
    };
  };
};

export type UpdateUserRolesResponse = UpdateUserRolesResponses[keyof UpdateUserRolesResponses];

export type DeactivateUserData = {
  body?: {
    /**
     * Reason for deactivation
     */
    reason?: string;
  };
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}/deactivate';
};

export type DeactivateUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type DeactivateUserError = DeactivateUserErrors[keyof DeactivateUserErrors];

export type DeactivateUserResponses = {
  /**
   * User deactivated
   */
  200: {
    success: boolean;
  };
};

export type DeactivateUserResponse = DeactivateUserResponses[keyof DeactivateUserResponses];

export type ActivateUserData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}/activate';
};

export type ActivateUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ActivateUserError = ActivateUserErrors[keyof ActivateUserErrors];

export type ActivateUserResponses = {
  /**
   * User activated
   */
  200: {
    success: boolean;
  };
};

export type ActivateUserResponse = ActivateUserResponses[keyof ActivateUserResponses];

export type UnlockUserData = {
  body?: never;
  path: {
    /**
     * User ID
     */
    userId: string;
  };
  query?: never;
  url: '/api/users/{userId}/unlock';
};

export type UnlockUserErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type UnlockUserError = UnlockUserErrors[keyof UnlockUserErrors];

export type UnlockUserResponses = {
  /**
   * User unlocked
   */
  200: {
    success: boolean;
  };
};

export type UnlockUserResponse = UnlockUserResponses[keyof UnlockUserResponses];

export type ListAuditLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by actor ID
     */
    actorId?: string;
    /**
     * End date (ISO 8601)
     */
    endDate?: string;
    /**
     * Filter by event (supports wildcard: auth.*)
     */
    event?: string;
    /**
     * Start date (ISO 8601)
     */
    startDate?: string;
    /**
     * Filter by target ID
     */
    targetId?: string;
    /**
     * Filter by target type
     */
    targetType?: 'role' | 'session' | 'user';
    /**
     * Sort order
     */
    order?: 'asc' | 'desc';
    /**
     * Page number (1-indexed)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    perPage?: number;
    /**
     * Sort by column
     */
    sort?: string;
  };
  url: '/api/audit-logs';
};

export type ListAuditLogsErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors];

export type ListAuditLogsResponses = {
  /**
   * Paginated audit logs
   */
  200: {
    data: Array<{
      actorId: string | null;
      actorType: 'api' | 'system' | 'user';
      createdAt: string;
      event: 'auth.login.failed' | 'auth.login.success' | 'auth.logout' | 'auth.password.changed' | 'auth.session.revoked' | 'role.assigned' | 'role.created' | 'role.deleted' | 'role.unassigned' | 'role.updated' | 'user.activated' | 'user.created' | 'user.deactivated' | 'user.deleted' | 'user.listed' | 'user.unlocked' | 'user.updated' | 'user.viewed';
      id: string;
      ipAddress: string | null;
      metadata: {
        [key: string]: unknown;
      } | null;
      targetId: string | null;
      targetType: 'role' | 'session' | 'user' | null;
      userAgent: string | null;
    }>;
    meta: {
      /**
       * Whether there is a next page
       */
      hasNext: boolean;
      /**
       * Whether there is a previous page
       */
      hasPrev: boolean;
      /**
       * Next page number or null
       */
      nextPage: number | null;
      /**
       * Current page number
       */
      page: number;
      /**
       * Total number of pages
       */
      pageCount: number;
      /**
       * Items per page
       */
      perPage: number;
      /**
       * Previous page number or null
       */
      prevPage: number | null;
      /**
       * Total number of items
       */
      total: number;
    };
  };
};

export type ListAuditLogsResponse = ListAuditLogsResponses[keyof ListAuditLogsResponses];

export type ListNotificationsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by channel
     */
    channel?: 'email' | 'sms' | 'push';
    /**
     * Sort by column
     */
    sort?: 'createdAt' | 'status' | 'type';
    /**
     * Filter by status
     */
    status?: 'pending' | 'sent' | 'delivered' | 'failed' | 'cancelled';
    /**
     * Filter by notification type
     */
    type?: string;
    /**
     * Only return unread notifications
     */
    unreadOnly?: string;
    /**
     * Sort order
     */
    order?: 'asc' | 'desc';
    /**
     * Page number (1-indexed)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    perPage?: number;
  };
  url: '/api/notifications';
};

export type ListNotificationsErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ListNotificationsError = ListNotificationsErrors[keyof ListNotificationsErrors];

export type ListNotificationsResponses = {
  /**
   * User notifications
   */
  200: {
    data: Array<{
      /**
       * Notification body text
       */
      body: string | null;
      /**
       * Delivery channel
       */
      channel: 'email' | 'sms' | 'push';
      /**
       * Created timestamp
       */
      createdAt: string;
      /**
       * When notification was delivered to device
       */
      deliveredAt: string | null;
      /**
       * Notification ID
       */
      id: string;
      /**
       * Whether the notification has been read. null for channels where read tracking is not available (e.g. email)
       */
      isRead: boolean | null;
      /**
       * Priority level
       */
      priority: 'low' | 'medium' | 'high' | 'critical';
      /**
       * Additional props for templates
       */
      props: {
        [key: string]: unknown;
      } | null;
      /**
       * When the notification was read by the user
       */
      readAt: string | null;
      /**
       * When notification was sent to provider
       */
      sentAt: string | null;
      /**
       * Delivery status
       */
      status: 'pending' | 'sent' | 'delivered' | 'failed' | 'cancelled';
      /**
       * Notification subject/title
       */
      subject: string | null;
      /**
       * Notification type
       */
      type: string;
    }>;
    meta: {
      /**
       * Whether there is a next page
       */
      hasNext: boolean;
      /**
       * Whether there is a previous page
       */
      hasPrev: boolean;
      /**
       * Next page number or null
       */
      nextPage: number | null;
      /**
       * Current page number
       */
      page: number;
      /**
       * Total number of pages
       */
      pageCount: number;
      /**
       * Items per page
       */
      perPage: number;
      /**
       * Previous page number or null
       */
      prevPage: number | null;
      /**
       * Total number of items
       */
      total: number;
    };
  };
};

export type ListNotificationsResponse = ListNotificationsResponses[keyof ListNotificationsResponses];

export type GetNotificationPreferencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notifications/preferences';
};

export type GetNotificationPreferencesErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type GetNotificationPreferencesError = GetNotificationPreferencesErrors[keyof GetNotificationPreferencesErrors];

export type GetNotificationPreferencesResponses = {
  /**
   * Preferences retrieved successfully
   */
  200: {
    preferences: {
      /**
       * Email notifications enabled
       */
      emailEnabled: boolean;
      /**
       * Push notifications enabled
       */
      pushEnabled: boolean;
      /**
       * SMS notifications enabled
       */
      smsEnabled: boolean;
      /**
       * Per-type notification preferences
       */
      typeOverrides: {
        [key: string]: {
          channels?: Array<'email' | 'sms' | 'push'>;
          enabled?: boolean;
        };
      } | null;
    };
  };
};

export type GetNotificationPreferencesResponse = GetNotificationPreferencesResponses[keyof GetNotificationPreferencesResponses];

export type UpdateNotificationPreferencesData = {
  body?: {
    /**
     * Enable email notifications
     */
    emailEnabled?: boolean;
    /**
     * Enable push notifications
     */
    pushEnabled?: boolean;
    /**
     * Enable SMS notifications
     */
    smsEnabled?: boolean;
    /**
     * Per-type notification preferences
     */
    typeOverrides?: {
      [key: string]: {
        channels?: Array<'email' | 'sms' | 'push'>;
        enabled?: boolean;
      };
    };
  };
  path?: never;
  query?: never;
  url: '/api/notifications/preferences';
};

export type UpdateNotificationPreferencesErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type UpdateNotificationPreferencesError = UpdateNotificationPreferencesErrors[keyof UpdateNotificationPreferencesErrors];

export type UpdateNotificationPreferencesResponses = {
  /**
   * Preferences updated successfully
   */
  200: {
    preferences: {
      /**
       * Email notifications enabled
       */
      emailEnabled: boolean;
      /**
       * Push notifications enabled
       */
      pushEnabled: boolean;
      /**
       * SMS notifications enabled
       */
      smsEnabled: boolean;
      /**
       * Per-type notification preferences
       */
      typeOverrides: {
        [key: string]: {
          channels?: Array<'email' | 'sms' | 'push'>;
          enabled?: boolean;
        };
      } | null;
    };
  };
};

export type UpdateNotificationPreferencesResponse = UpdateNotificationPreferencesResponses[keyof UpdateNotificationPreferencesResponses];

export type GetNotificationData = {
  body?: never;
  path: {
    /**
     * Notification ID
     */
    notificationId: string;
  };
  query?: never;
  url: '/api/notifications/{notificationId}';
};

export type GetNotificationErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type GetNotificationError = GetNotificationErrors[keyof GetNotificationErrors];

export type GetNotificationResponses = {
  /**
   * Notification retrieved successfully
   */
  200: {
    notification: {
      /**
       * Notification body text
       */
      body: string | null;
      /**
       * Delivery channel
       */
      channel: 'email' | 'sms' | 'push';
      /**
       * Created timestamp
       */
      createdAt: string;
      /**
       * When notification was delivered to device
       */
      deliveredAt: string | null;
      /**
       * Notification ID
       */
      id: string;
      /**
       * Whether the notification has been read. null for channels where read tracking is not available (e.g. email)
       */
      isRead: boolean | null;
      /**
       * Priority level
       */
      priority: 'low' | 'medium' | 'high' | 'critical';
      /**
       * Additional props for templates
       */
      props: {
        [key: string]: unknown;
      } | null;
      /**
       * When the notification was read by the user
       */
      readAt: string | null;
      /**
       * When notification was sent to provider
       */
      sentAt: string | null;
      /**
       * Delivery status
       */
      status: 'pending' | 'sent' | 'delivered' | 'failed' | 'cancelled';
      /**
       * Notification subject/title
       */
      subject: string | null;
      /**
       * Notification type
       */
      type: string;
    };
  };
};

export type GetNotificationResponse = GetNotificationResponses[keyof GetNotificationResponses];

export type GetUnreadNotificationCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notifications/unread/count';
};

export type GetUnreadNotificationCountErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type GetUnreadNotificationCountError = GetUnreadNotificationCountErrors[keyof GetUnreadNotificationCountErrors];

export type GetUnreadNotificationCountResponses = {
  /**
   * Unread count retrieved successfully
   */
  200: {
    /**
     * Number of unread notifications
     */
    count: number;
  };
};

export type GetUnreadNotificationCountResponse = GetUnreadNotificationCountResponses[keyof GetUnreadNotificationCountResponses];

export type MarkNotificationAsReadData = {
  body?: never;
  path: {
    /**
     * Notification ID
     */
    notificationId: string;
  };
  query?: never;
  url: '/api/notifications/{notificationId}/read';
};

export type MarkNotificationAsReadErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type MarkNotificationAsReadError = MarkNotificationAsReadErrors[keyof MarkNotificationAsReadErrors];

export type MarkNotificationAsReadResponses = {
  /**
   * Notification marked as read
   */
  200: {
    /**
     * Operation success status
     */
    success: boolean;
  };
};

export type MarkNotificationAsReadResponse = MarkNotificationAsReadResponses[keyof MarkNotificationAsReadResponses];

export type MarkAllNotificationsAsReadData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notifications/read-all';
};

export type MarkAllNotificationsAsReadErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type MarkAllNotificationsAsReadError = MarkAllNotificationsAsReadErrors[keyof MarkAllNotificationsAsReadErrors];

export type MarkAllNotificationsAsReadResponses = {
  /**
   * All notifications marked as read
   */
  200: {
    /**
     * Number of notifications marked as read
     */
    markedCount: number;
    /**
     * Operation success status
     */
    success: boolean;
  };
};

export type MarkAllNotificationsAsReadResponse = MarkAllNotificationsAsReadResponses[keyof MarkAllNotificationsAsReadResponses];

export type ListPushTokensData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/notifications/push-tokens';
};

export type ListPushTokensErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type ListPushTokensError = ListPushTokensErrors[keyof ListPushTokensErrors];

export type ListPushTokensResponses = {
  /**
   * Push tokens retrieved successfully
   */
  200: {
    tokens: Array<{
      /**
       * Created timestamp
       */
      createdAt: string;
      /**
       * Device identifier
       */
      deviceId: string | null;
      /**
       * Device name
       */
      deviceName: string | null;
      /**
       * Push token ID
       */
      id: string;
      /**
       * Whether token is active
       */
      isActive: boolean;
      /**
       * Last time token was used
       */
      lastUsedAt: string | null;
      /**
       * Device platform
       */
      platform: 'ios' | 'android' | 'web';
      /**
       * Associated session ID
       */
      sessionId: string | null;
    }>;
  };
};

export type ListPushTokensResponse = ListPushTokensResponses[keyof ListPushTokensResponses];

export type RegisterPushTokenData = {
  body?: {
    /**
     * Unique device identifier
     */
    deviceId?: string;
    /**
     * Human-readable device name
     */
    deviceName?: string;
    /**
     * Device platform
     */
    platform: 'ios' | 'android' | 'web';
    /**
     * FCM/APNs push token
     */
    token: string;
  };
  path?: never;
  query?: never;
  url: '/api/notifications/push-tokens';
};

export type RegisterPushTokenErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type RegisterPushTokenError = RegisterPushTokenErrors[keyof RegisterPushTokenErrors];

export type RegisterPushTokenResponses = {
  /**
   * Push token registered successfully
   */
  201: {
    token: {
      /**
       * Created timestamp
       */
      createdAt: string;
      /**
       * Device identifier
       */
      deviceId: string | null;
      /**
       * Device name
       */
      deviceName: string | null;
      /**
       * Push token ID
       */
      id: string;
      /**
       * Whether token is active
       */
      isActive: boolean;
      /**
       * Last time token was used
       */
      lastUsedAt: string | null;
      /**
       * Device platform
       */
      platform: 'ios' | 'android' | 'web';
      /**
       * Associated session ID
       */
      sessionId: string | null;
    };
  };
};

export type RegisterPushTokenResponse = RegisterPushTokenResponses[keyof RegisterPushTokenResponses];

export type DeletePushTokenData = {
  body?: never;
  path: {
    /**
     * Push token ID
     */
    tokenId: string;
  };
  query?: never;
  url: '/api/notifications/push-tokens/{tokenId}';
};

export type DeletePushTokenErrors = {
  /**
   * Bad request: problem processing request.
   */
  400: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unauthorized: authentication required.
   */
  401: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Forbidden: insufficient permissions.
   */
  403: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Not found: resource does not exist.
   */
  404: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Conflict: the request conflicts with current state (e.g. unique constraint violation).
   */
  409: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Unprocessable entity: request body failed validation (Zod schema).
   */
  422: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Too many requests: rate limit exceeded.
   */
  429: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Server error: something went wrong.
   */
  500: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
  /**
   * Service unavailable: dependency is not currently available.
   */
  503: {
    error: {
      code?: string;
      details?: string;
      message?: string;
    };
  };
};

export type DeletePushTokenError = DeletePushTokenErrors[keyof DeletePushTokenErrors];

export type DeletePushTokenResponses = {
  /**
   * Push token deleted successfully
   */
  200: {
    /**
     * Operation success status
     */
    success: boolean;
  };
};

export type DeletePushTokenResponse = DeletePushTokenResponses[keyof DeletePushTokenResponses];

export type GetAuthorizationCapabilitiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/authorization/capabilities';
};

export type GetAuthorizationCapabilitiesErrors = {
  /**
   * Unauthorized
   */
  401: {
    error: {
      code: string;
      message: string;
    };
  };
};

export type GetAuthorizationCapabilitiesError = GetAuthorizationCapabilitiesErrors[keyof GetAuthorizationCapabilitiesErrors];

export type GetAuthorizationCapabilitiesResponses = {
  /**
   * User capabilities
   */
  200: {
    capabilities: {
      [key: string]: boolean;
    };
  };
};

export type GetAuthorizationCapabilitiesResponse = GetAuthorizationCapabilitiesResponses[keyof GetAuthorizationCapabilitiesResponses];
