// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Roles
 */
export const zListRolesResponse = z.object({
    roles: z.array(z.object({
        slug: z.string(),
        name: z.string(),
        description: z.string(),
        permissions: z.array(z.enum([
            'dashboard:access',
            'users:view',
            'users:create',
            'users:update',
            'users:delete',
            'users:deactivate',
            'users:activate',
            'users:unlock',
            'roles:view',
            'roles:update',
            'audit-logs:view'
        ]))
    }))
});

export const zListUsersQuery = z.object({
    search: z.string().optional(),
    status: z.enum([
        'active',
        'inactive',
        'locked'
    ]).optional(),
    role: z.string().optional(),
    sort: z.string().optional(),
    page: z.number().gte(1).optional().default(1),
    perPage: z.number().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Paginated users list
 */
export const zListUsersResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        status: z.enum([
            'active',
            'inactive',
            'locked'
        ]),
        roleSlugs: z.array(z.string()),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    })),
    meta: z.object({
        total: z.number(),
        page: z.number(),
        perPage: z.number(),
        pageCount: z.number(),
        hasNext: z.boolean(),
        hasPrev: z.boolean(),
        nextPage: z.number().nullable(),
        prevPage: z.number().nullable()
    })
});

export const zCreateUserBody = z.object({
    name: z.string().min(1).max(100),
    email: z.email(),
    password: z.string().min(8).max(72),
    roleSlugs: z.array(z.string()).min(1)
});

/**
 * User created
 */
export const zCreateUserResponse = z.object({
    user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        status: z.enum([
            'active',
            'inactive',
            'locked'
        ]),
        roleSlugs: z.array(z.string()),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    })
});

/**
 * Current user account
 */
export const zGetMyAccountResponse = z.object({
    profile: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        onboardingCompletedAt: z.iso.datetime().nullable(),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    }),
    notifications: z.object({
        unreadCount: z.int()
    })
});

export const zGetUserPath = z.object({
    userId: z.string().min(1)
});

/**
 * User details
 */
export const zGetUserResponse = z.object({
    user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        status: z.enum([
            'active',
            'inactive',
            'locked'
        ]),
        roleSlugs: z.array(z.string()),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime(),
        failedLoginAttempts: z.number(),
        lockedUntil: z.iso.datetime().nullable(),
        deactivatedAt: z.iso.datetime().nullable(),
        deactivatedBy: z.string().nullable(),
        deactivatedReason: z.string().nullable()
    })
});

export const zUpdateUserBody = z.object({
    name: z.string().min(1).max(100).optional(),
    email: z.email().optional()
});

export const zUpdateUserPath = z.object({
    userId: z.string().min(1)
});

/**
 * User updated
 */
export const zUpdateUserResponse = z.object({
    user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        status: z.enum([
            'active',
            'inactive',
            'locked'
        ]),
        roleSlugs: z.array(z.string()),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    })
});

export const zUpdateUserRolesBody = z.object({
    roleSlugs: z.array(z.string()).min(1)
});

export const zUpdateUserRolesPath = z.object({
    userId: z.string().min(1)
});

/**
 * Roles updated
 */
export const zUpdateUserRolesResponse = z.object({
    user: z.object({
        id: z.string(),
        name: z.string(),
        email: z.email(),
        emailVerified: z.boolean(),
        image: z.string().nullable(),
        status: z.enum([
            'active',
            'inactive',
            'locked'
        ]),
        roleSlugs: z.array(z.string()),
        createdAt: z.iso.datetime(),
        updatedAt: z.iso.datetime()
    })
});

export const zDeactivateUserBody = z.object({
    reason: z.string().max(500).optional()
});

export const zDeactivateUserPath = z.object({
    userId: z.string().min(1)
});

/**
 * User deactivated
 */
export const zDeactivateUserResponse = z.object({
    success: z.boolean()
});

export const zActivateUserPath = z.object({
    userId: z.string().min(1)
});

/**
 * User activated
 */
export const zActivateUserResponse = z.object({
    success: z.boolean()
});

export const zUnlockUserPath = z.object({
    userId: z.string().min(1)
});

/**
 * User unlocked
 */
export const zUnlockUserResponse = z.object({
    success: z.boolean()
});

export const zListAuditLogsQuery = z.object({
    event: z.string().optional(),
    actorId: z.string().optional(),
    targetId: z.string().optional(),
    targetType: z.enum([
        'user',
        'role',
        'session'
    ]).optional(),
    startDate: z.iso.datetime().optional(),
    endDate: z.iso.datetime().optional(),
    page: z.number().gte(1).optional().default(1),
    perPage: z.number().gte(1).lte(100).optional().default(20),
    sort: z.string().optional(),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * Paginated audit logs
 */
export const zListAuditLogsResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        event: z.enum([
            'auth.login.success',
            'auth.login.failed',
            'auth.logout',
            'auth.password.changed',
            'auth.session.revoked',
            'user.created',
            'user.updated',
            'user.deleted',
            'user.deactivated',
            'user.activated',
            'user.unlocked',
            'user.viewed',
            'user.listed',
            'role.created',
            'role.updated',
            'role.deleted',
            'role.assigned',
            'role.unassigned'
        ]),
        actorId: z.string().nullable(),
        actorType: z.enum([
            'user',
            'system',
            'api'
        ]),
        targetId: z.string().nullable(),
        targetType: z.enum([
            'user',
            'role',
            'session'
        ]).nullable(),
        ipAddress: z.string().nullable(),
        userAgent: z.string().nullable(),
        metadata: z.record(z.string(), z.unknown()).nullable(),
        createdAt: z.iso.datetime()
    })),
    meta: z.object({
        total: z.number(),
        page: z.number(),
        perPage: z.number(),
        pageCount: z.number(),
        hasNext: z.boolean(),
        hasPrev: z.boolean(),
        nextPage: z.number().nullable(),
        prevPage: z.number().nullable()
    })
});

export const zListNotificationsQuery = z.object({
    type: z.string().optional(),
    status: z.enum([
        'pending',
        'sent',
        'delivered',
        'failed',
        'cancelled'
    ]).optional(),
    channel: z.enum([
        'email',
        'sms',
        'push'
    ]).optional(),
    unreadOnly: z.string().optional(),
    sort: z.enum([
        'createdAt',
        'status',
        'type'
    ]).optional(),
    page: z.number().gte(1).optional().default(1),
    perPage: z.number().gte(1).lte(100).optional().default(20),
    order: z.enum(['asc', 'desc']).optional().default('desc')
});

/**
 * User notifications
 */
export const zListNotificationsResponse = z.object({
    data: z.array(z.object({
        id: z.string(),
        type: z.string(),
        channel: z.enum([
            'email',
            'sms',
            'push'
        ]),
        status: z.enum([
            'pending',
            'sent',
            'delivered',
            'failed',
            'cancelled'
        ]),
        priority: z.enum([
            'low',
            'medium',
            'high',
            'critical'
        ]),
        subject: z.string().nullable(),
        body: z.string().nullable(),
        props: z.record(z.string(), z.unknown()).nullable(),
        isRead: z.boolean().nullable(),
        readAt: z.iso.datetime().nullable(),
        sentAt: z.iso.datetime().nullable(),
        deliveredAt: z.iso.datetime().nullable(),
        createdAt: z.iso.datetime()
    })),
    meta: z.object({
        total: z.number(),
        page: z.number(),
        perPage: z.number(),
        pageCount: z.number(),
        hasNext: z.boolean(),
        hasPrev: z.boolean(),
        nextPage: z.number().nullable(),
        prevPage: z.number().nullable()
    })
});

/**
 * Preferences retrieved successfully
 */
export const zGetNotificationPreferencesResponse = z.object({
    preferences: z.object({
        emailEnabled: z.boolean(),
        smsEnabled: z.boolean(),
        pushEnabled: z.boolean(),
        typeOverrides: z.record(z.string(), z.object({
            channels: z.array(z.enum([
                'email',
                'sms',
                'push'
            ])).optional(),
            enabled: z.boolean().optional()
        })).nullable()
    })
});

export const zUpdateNotificationPreferencesBody = z.object({
    emailEnabled: z.boolean().optional(),
    smsEnabled: z.boolean().optional(),
    pushEnabled: z.boolean().optional(),
    typeOverrides: z.record(z.string(), z.object({
        channels: z.array(z.enum([
            'email',
            'sms',
            'push'
        ])).optional(),
        enabled: z.boolean().optional()
    })).optional()
});

/**
 * Preferences updated successfully
 */
export const zUpdateNotificationPreferencesResponse = z.object({
    preferences: z.object({
        emailEnabled: z.boolean(),
        smsEnabled: z.boolean(),
        pushEnabled: z.boolean(),
        typeOverrides: z.record(z.string(), z.object({
            channels: z.array(z.enum([
                'email',
                'sms',
                'push'
            ])).optional(),
            enabled: z.boolean().optional()
        })).nullable()
    })
});

export const zGetNotificationPath = z.object({
    notificationId: z.string().min(1)
});

/**
 * Notification retrieved successfully
 */
export const zGetNotificationResponse = z.object({
    notification: z.object({
        id: z.string(),
        type: z.string(),
        channel: z.enum([
            'email',
            'sms',
            'push'
        ]),
        status: z.enum([
            'pending',
            'sent',
            'delivered',
            'failed',
            'cancelled'
        ]),
        priority: z.enum([
            'low',
            'medium',
            'high',
            'critical'
        ]),
        subject: z.string().nullable(),
        body: z.string().nullable(),
        props: z.record(z.string(), z.unknown()).nullable(),
        isRead: z.boolean().nullable(),
        readAt: z.iso.datetime().nullable(),
        sentAt: z.iso.datetime().nullable(),
        deliveredAt: z.iso.datetime().nullable(),
        createdAt: z.iso.datetime()
    })
});

/**
 * Unread count retrieved successfully
 */
export const zGetUnreadNotificationCountResponse = z.object({
    count: z.int().gte(0)
});

export const zMarkNotificationAsReadPath = z.object({
    notificationId: z.string().min(1)
});

/**
 * Notification marked as read
 */
export const zMarkNotificationAsReadResponse = z.object({
    success: z.boolean()
});

/**
 * All notifications marked as read
 */
export const zMarkAllNotificationsAsReadResponse = z.object({
    success: z.boolean(),
    markedCount: z.int()
});

/**
 * Push tokens retrieved successfully
 */
export const zListPushTokensResponse = z.object({
    tokens: z.array(z.object({
        id: z.string(),
        platform: z.enum([
            'ios',
            'android',
            'web'
        ]),
        deviceId: z.string().nullable(),
        deviceName: z.string().nullable(),
        isActive: z.boolean(),
        lastUsedAt: z.iso.datetime().nullable(),
        createdAt: z.iso.datetime(),
        sessionId: z.string()
    }))
});

export const zRegisterPushTokenBody = z.object({
    token: z.string().min(1),
    platform: z.enum([
        'ios',
        'android',
        'web'
    ]),
    deviceId: z.string().optional(),
    deviceName: z.string().max(100).optional()
});

/**
 * Push token registered successfully
 */
export const zRegisterPushTokenResponse = z.object({
    token: z.object({
        id: z.string(),
        platform: z.enum([
            'ios',
            'android',
            'web'
        ]),
        deviceId: z.string().nullable(),
        deviceName: z.string().nullable(),
        isActive: z.boolean(),
        lastUsedAt: z.iso.datetime().nullable(),
        createdAt: z.iso.datetime(),
        sessionId: z.string()
    })
});

export const zDeletePushTokenPath = z.object({
    tokenId: z.string().min(1)
});

/**
 * Push token deleted successfully
 */
export const zDeletePushTokenResponse = z.object({
    success: z.boolean()
});

/**
 * User capabilities
 */
export const zGetAuthorizationCapabilitiesResponse = z.object({
    capabilities: z.record(z.string(), z.boolean())
});
