// Widen NODE_ENV from the literal "development" generated by wrangler types.
// At deploy time, --var NODE_ENV:production overrides it.
declare global {
  // biome-ignore lint/style/noNamespace: required for NodeJS.ProcessEnv augmentation
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: string;
    }
  }
}

export type {};
