// Widen NODE_ENV from the literal "production" generated by wrangler.
// At runtime, .dev.vars may override it to "development" or "test".
declare global {
  // biome-ignore lint/style/noNamespace: required for NodeJS.ProcessEnv augmentation
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV: string;
    }
  }
}

export type {};
