// A7.1 — generator output snapshots. Drives `runSetupEnv` against the
// baseline fixture into a tmp dir, then asserts the per-target artifacts
// contain the values the spec calls out.

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BASELINE_FIXTURE } from "../lib/__tests__/host-config.fixture";
import { runSetupEnv } from "../setup-env";

let tmpDir: string;

beforeAll(async () => {
  tmpDir = mkdtempSync(join(tmpdir(), "setup-env-test-"));
  await runSetupEnv({ fixture: BASELINE_FIXTURE, outDir: tmpDir });
});

afterAll(() => {
  if (tmpDir) {
    rmSync(tmpDir, { recursive: true, force: true });
  }
});

function read(rel: string): string {
  return readFileSync(join(tmpDir, rel), "utf8");
}

describe("runSetupEnv (baseline fixture)", () => {
  test("server wrangler vars fragment carries the local hosts", () => {
    const text = read("apps/server/wrangler.jsonc.fragment.json");
    expect(text).toContain("GENERATED by bun run setup:env");
    const json = JSON.parse(text.split("\n").slice(1).join("\n")) as {
      vars: Record<string, string>;
    };
    expect(json.vars.WILDCARD_SUFFIX).toBe(".app.lvh.me");
    expect(json.vars.ADMIN_HOST).toBe("admin.lvh.me");
    expect(json.vars.FALLBACK_HOST).toBe("fallback.lvh.me");
    expect(json.vars.CUSTOM_HOST_CNAME_TARGET).toBe("customers.example.com");
    expect(json.vars.CUSTOM_HOST_VERIFICATION_LABEL).toBe(
      "_app-example-verify"
    );
    expect(json.vars.BRANDING_HOST).toBe("branding.example.com");
  });

  test("auth wrangler vars fragment carries the local hosts only", () => {
    const text = read("apps/auth/wrangler.jsonc.fragment.json");
    const json = JSON.parse(text.split("\n").slice(1).join("\n")) as {
      vars: Record<string, string>;
    };
    expect(json.vars.WILDCARD_SUFFIX).toBe(".app.lvh.me");
    expect(json.vars.ADMIN_HOST).toBe("admin.lvh.me");
  });

  test("server .dev.vars.tenancy enables the dev-tenant header gate", () => {
    const text = read("apps/server/.dev.vars.tenancy");
    expect(text).toContain("ALLOW_DEV_TENANT_HEADER=true");
    expect(text).toContain("ALLOW_DEV_TENANT_AUTH=false");
  });

  test("admin-ui .env.development carries the local app/admin hosts and dev slug", () => {
    const text = read("apps/admin-ui/.env.development");
    expect(text).toContain("VITE_APP_WILDCARD_HOST=app.lvh.me");
    expect(text).toContain("VITE_ADMIN_HOST=admin.lvh.me");
    expect(text).toContain("VITE_DEV_TENANT_SLUG=acme");
  });

  test("Caddyfile contains *.app.lvh.me and admin.lvh.me blocks", () => {
    const text = read("local-harness/Caddyfile");
    expect(text).toContain("*.app.lvh.me {");
    expect(text).toContain("admin.lvh.me {");
    expect(text).toContain("reverse_proxy localhost:8787"); // server
    expect(text).toContain("reverse_proxy localhost:8788"); // auth
    expect(text).toContain("reverse_proxy localhost:3001"); // web
    expect(text).toContain("header_up Host {host}");
  });

  test("mkcert SAN list contains the wildcard, admin, and lvh.me apex", () => {
    const text = read("local-harness/mkcert-sans.txt");
    const lines = text.split("\n").filter((l) => l.length > 0);
    expect(lines).toContain("*.app.lvh.me");
    expect(lines).toContain("admin.lvh.me");
    expect(lines).toContain("lvh.me");
  });
});

describe("runSetupEnv merges fragment into wrangler.jsonc", () => {
  test("preserves comments and updates vars in-place", async () => {
    const tmp = mkdtempSync(join(tmpdir(), "setup-env-merge-"));
    try {
      mkdirSync(join(tmp, "apps/server"), { recursive: true });
      const original = `{
  // This comment must survive the merge.
  "name": "server",
  "vars": {
    "NODE_ENV": "development",
    // host config — managed by setup-env
    "WILDCARD_SUFFIX": ".old.example.com",
    "ADMIN_HOST": "old.example.com"
  }
}
`;
      writeFileSync(join(tmp, "apps/server/wrangler.jsonc"), original, "utf8");
      const result = await runSetupEnv({
        fixture: BASELINE_FIXTURE,
        outDir: tmp,
      });
      expect(result.mergedWranglers).toContain("apps/server/wrangler.jsonc");
      const merged = readFileSync(
        join(tmp, "apps/server/wrangler.jsonc"),
        "utf8"
      );
      // Comments preserved.
      expect(merged).toContain("This comment must survive the merge.");
      expect(merged).toContain("host config — managed by setup-env");
      // Values rewritten.
      expect(merged).toContain('"WILDCARD_SUFFIX": ".app.lvh.me"');
      expect(merged).toContain('"ADMIN_HOST": "admin.lvh.me"');
      // Untouched keys remain.
      expect(merged).toContain('"NODE_ENV": "development"');
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});
