import {
  SYSTEM_ROLE_SLUG_VALUES as SHARED_SYSTEM_ROLE_SLUG_VALUES,
  SYSTEM_ROLES as SHARED_SYSTEM_ROLES,
} from "@repo/shared/authorization";

export const SYSTEM_ROLES = SHARED_SYSTEM_ROLES;
export const SYSTEM_ROLE_SLUG_VALUES = SHARED_SYSTEM_ROLE_SLUG_VALUES;
