// This file is auto-generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app.index"
import { Route as AppSystemRouteImport } from "./routes/_app.system"
import { Route as AppGlobalAdminsRouteImport } from "./routes/_app.global-admins"
import { Route as AppAuditLogsRouteImport } from "./routes/_app.audit-logs"
import { Route as AppTenantsIndexRouteImport } from "./routes/_app.tenants.index"
import { Route as AppTenantsNewRouteImport } from "./routes/_app.tenants.new"
import { Route as AppTenantsSlugRouteImport } from "./routes/_app.tenants.$slug"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: "/system",
  path: "/system",
  getParentRoute: () => AppRoute,
} as any)
const AppGlobalAdminsRoute = AppGlobalAdminsRouteImport.update({
  id: "/global-admins",
  path: "/global-admins",
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: "/audit-logs",
  path: "/audit-logs",
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: "/tenants/",
  path: "/tenants/",
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsNewRoute = AppTenantsNewRouteImport.update({
  id: "/tenants/new",
  path: "/tenants/new",
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsSlugRoute = AppTenantsSlugRouteImport.update({
  id: "/tenants/$slug",
  path: "/tenants/$slug",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/audit-logs": typeof AppAuditLogsRoute
  "/global-admins": typeof AppGlobalAdminsRoute
  "/system": typeof AppSystemRoute
  "/tenants/$slug": typeof AppTenantsSlugRoute
  "/tenants/new": typeof AppTenantsNewRoute
  "/tenants/": typeof AppTenantsIndexRoute
}
export interface FileRoutesByTo {
  "/audit-logs": typeof AppAuditLogsRoute
  "/global-admins": typeof AppGlobalAdminsRoute
  "/system": typeof AppSystemRoute
  "/": typeof AppIndexRoute
  "/tenants/$slug": typeof AppTenantsSlugRoute
  "/tenants/new": typeof AppTenantsNewRoute
  "/tenants": typeof AppTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/_app/audit-logs": typeof AppAuditLogsRoute
  "/_app/global-admins": typeof AppGlobalAdminsRoute
  "/_app/system": typeof AppSystemRoute
  "/_app/": typeof AppIndexRoute
  "/_app/tenants/$slug": typeof AppTenantsSlugRoute
  "/_app/tenants/new": typeof AppTenantsNewRoute
  "/_app/tenants/": typeof AppTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/audit-logs"
    | "/global-admins"
    | "/system"
    | "/tenants/$slug"
    | "/tenants/new"
    | "/tenants/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/audit-logs"
    | "/global-admins"
    | "/system"
    | "/"
    | "/tenants/$slug"
    | "/tenants/new"
    | "/tenants"
  id:
    | "__root__"
    | "/_app"
    | "/_app/audit-logs"
    | "/_app/global-admins"
    | "/_app/system"
    | "/_app/"
    | "/_app/tenants/$slug"
    | "/_app/tenants/new"
    | "/_app/tenants/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/system": {
      id: "/_app/system"
      path: "/system"
      fullPath: "/system"
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/global-admins": {
      id: "/_app/global-admins"
      path: "/global-admins"
      fullPath: "/global-admins"
      preLoaderRoute: typeof AppGlobalAdminsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/audit-logs": {
      id: "/_app/audit-logs"
      path: "/audit-logs"
      fullPath: "/audit-logs"
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tenants/": {
      id: "/_app/tenants/"
      path: "/tenants"
      fullPath: "/tenants/"
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tenants/new": {
      id: "/_app/tenants/new"
      path: "/tenants/new"
      fullPath: "/tenants/new"
      preLoaderRoute: typeof AppTenantsNewRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tenants/$slug": {
      id: "/_app/tenants/$slug"
      path: "/tenants/$slug"
      fullPath: "/tenants/$slug"
      preLoaderRoute: typeof AppTenantsSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppGlobalAdminsRoute: typeof AppGlobalAdminsRoute
  AppSystemRoute: typeof AppSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTenantsSlugRoute: typeof AppTenantsSlugRoute
  AppTenantsNewRoute: typeof AppTenantsNewRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppGlobalAdminsRoute: AppGlobalAdminsRoute,
  AppSystemRoute: AppSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppTenantsSlugRoute: AppTenantsSlugRoute,
  AppTenantsNewRoute: AppTenantsNewRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
